#!/bin/bash

# kubctl-0x01
# Script to scale Django messaging app in Kubernetes and perform load testing

set -e

DEPLOYMENT_NAME="django-messaging-deployment"
SERVICE_NAME="django-messaging-service"
NAMESPACE="default"

echo "=== Scaling deployment $DEPLOYMENT_NAME to 3 replicas... ==="
kubectl scale deployment $DEPLOYMENT_NAME --replicas=3 --namespace=$NAMESPACE

echo "=== Verifying running pods... ==="
kubectl get pods -l app=django-messaging -o wide --namespace=$NAMESPACE

echo "=== Waiting for all pods to be ready... ==="
kubectl rollout status deployment/$DEPLOYMENT_NAME --namespace=$NAMESPACE

echo "=== Checking service details... ==="
kubectl get svc $SERVICE_NAME --namespace=$NAMESPACE

# Get ClusterIP and Port of the service
CLUSTER_IP=$(kubectl get svc $SERVICE_NAME --namespace=$NAMESPACE -o jsonpath='{.spec.clusterIP}')
PORT=$(kubectl get svc $SERVICE_NAME --namespace=$NAMESPACE -o jsonpath='{.spec.ports[0].port}')

echo "=== Running load test using wrk... ==="
echo "Testing $CLUSTER_IP:$PORT for 10 seconds..."
wrk -t2 -c50 -d10s http://$CLUSTER_IP:$PORT/

echo "=== Monitoring resource usage... ==="
kubectl top pods --namespace=$NAMESPACE
