pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', 
                    url: 'https://github.com/derickmokua/alx-backend-python.git'
            }
        }
        stage('Install dependencies & Run Tests') {
            steps {
                sh '''
                pip install -r messaging_app/requirements.txt
                pytest messaging_app/tests --junitxml=report.xml
                '''
            }
        }
    }
    post {
        always {
            junit 'report.xml'
        }
    }
}
stage('Build Docker Image') {
    steps {
        script {
            docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-credentials') {
                def app = docker.build("your-dockerhub-username/messaging_app:${env.BUILD_NUMBER}")
                app.push()
                app.push("latest")
            }
        }
    }
}
